=== UNA-UNDERGROUND/proyecto-1-estructuras-datos-java-2021/src/test/resources/sparse_matrix.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="sparse_matrix">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entry_list"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entry_list">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="entry"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="row"/>
        <xs:element ref="column"/>
        <xs:element ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="row" type="xs:integer"/>
  <xs:element name="column" type="xs:integer"/>
  <xs:element name="value" type="xs:string"/>
</xs:schema>

=== UNA-UNDERGROUND/proyecto-1-estructuras-datos-java-2021/assets/B.xml
<?xml version="1.0" encoding="UTF-8"?>
<sparse_matrix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="sparse_matrix.xsd">
    <entry_list>
        <entry>
            <row>0</row>
            <column>1</column>
            <value>312</value>
        </entry>
        <entry>
            <row>0</row>
            <column>21</column>
            <value>302</value>
        </entry>
        <entry>
            <row>0</row>
            <column>124</column>
            <value>219</value>
        </entry>
        <entry>
            <row>0</row>
            <column>134</column>
            <value>182</value>
        </entry>
        <entry>
            <row>0</row>
            <column>198</column>
            <value>293</value>
        </entry>
        <entry>
            <row>1</row>
            <column>35</column>
            <value>67</value>
        </entry>
        <entry>
            <row>1</row>
            <column>64</column>
            <value>7</value>
        </entry>
        <entry>
            <row>1</row>
            <column>80</column>
            <value>143</value>
        </entry>
        <entry>
            <row>1</row>
            <column>177</column>
            <value>4</value>
        </entry>
        <entry>
            <row>1</row>
            <column>186</column>
            <value>236</value>
        </entry>
        <entry>
            <row>1</row>
            <column>196</column>
            <value>193</value>
        </entry>
        <entry>
            <row>2</row>
            <column>24</column>
            <value>219</value>
        </entry>
        <entry>
            <row>2</row>
            <column>123</column>
            <value>238</value>
        </entry>
        <entry>
            <row>3</row>
            <column>74</column>
            <value>83</value>
        </entry>
        <entry>
            <row>3</row>
            <column>133</column>
            <value>256</value>
        </entry>
        <entry>
            <row>3</row>
            <column>140</column>
            <value>338</value>
        </entry>
        <entry>
            <row>4</row>
            <column>32</column>
            <value>35</value>
        </entry>
        <entry>
            <row>4</row>
            <column>55</column>
            <value>193</value>
        </entry>
        <entry>
            <row>4</row>
            <column>64</column>
            <value>245</value>
        </entry>
        <entry>
            <row>4</row>
            <column>75</column>
            <value>267</value>
        </entry>
        <entry>
            <row>4</row>
            <column>95</column>
            <value>12</value>
        </entry>
        <entry>
            <row>4</row>
            <column>223</column>
            <value>9</value>
        </entry>
        <entry>
            <row>4</row>
            <column>239</column>
            <value>188</value>
        </entry>
        <entry>
            <row>5</row>
            <column>24</column>
            <value>270</value>
        </entry>
        <entry>
            <row>5</row>
            <column>30</column>
            <value>139</value>
        </entry>
        <entry>
            <row>5</row>
            <column>53</column>
            <value>1</value>
        </entry>
        <entry>
            <row>5</row>
            <column>133</column>
            <value>30</value>
        </entry>
        <entry>
            <row>5</row>
            <column>137</column>
            <value>246</value>
        </entry>
        <entry>
            <row>5</row>
            <column>189</column>
            <value>218</value>
        </entry>
        <entry>
            <row>5</row>
            <column>220</column>
            <value>22</value>
        </entry>
        <entry>
            <row>6</row>
            <column>44</column>
            <value>265</value>
        </entry>
        <entry>
            <row>6</row>
            <column>119</column>
            <value>326</value>
        </entry>
        <entry>
            <row>6</row>
            <column>206</column>
            <value>102</value>
        </entry>
        <entry>
            <row>7</row>
            <column>20</column>
            <value>112</value>
        </entry>
        <entry>
            <row>7</row>
            <column>179</column>
            <value>116</value>
        </entry>
        <entry>
            <row>7</row>
            <column>231</column>
            <value>261</value>
        </entry>
        <entry>
            <row>8</row>
            <column>23</column>
            <value>39</value>
        </entry>
        <entry>
            <row>8</row>
            <column>29</column>
            <value>323</value>
        </entry>
        <entry>
            <row>8</row>
            <column>229</column>
            <value>138</value>
        </entry>
        <entry>
            <row>9</row>
            <column>176</column>
            <value>79</value>
        </entry>
        <entry>
            <row>9</row>
            <column>234</column>
            <value>21</value>
        </entry>
        <entry>
            <row>10</row>
            <column>1</column>
            <value>260</value>
        </entry>
        <entry>
            <row>10</row>
            <column>16</column>
            <value>269</value>
        </entry>
        <entry>
            <row>10</row>
            <column>51</column>
            <value>230</value>
        </entry>
        <entry>
            <row>10</row>
            <column>65</column>
            <value>203</value>
        </entry>
        <entry>
            <row>10</row>
            <column>67</column>
            <value>148</value>
        </entry>
        <entry>
            <row>10</row>
            <column>73</column>
            <value>271</value>
        </entry>
        <entry>
            <row>10</row>
            <column>112</column>
            <value>320</value>
        </entry>
        <entry>
            <row>10</row>
            <column>142</column>
            <value>231</value>
        </entry>
        <entry>
            <row>10</row>
            <column>149</column>
            <value>225</value>
        </entry>
        <entry>
            <row>10</row>
            <column>185</column>
            <value>38</value>
        </entry>
        <entry>
            <row>10</row>
            <column>237</column>
            <value>285</value>
        </entry>
        <entry>
            <row>11</row>
            <column>89</column>
            <value>142</value>
        </entry>
        <entry>
            <row>11</row>
            <column>98</column>
            <value>325</value>
        </entry>
        <entry>
            <row>11</row>
            <column>131</column>
            <value>6</value>
        </entry>
        <entry>
            <row>11</row>
            <column>143</column>
            <value>168</value>
        </entry>
        <entry>
            <row>11</row>
            <column>232</column>
            <value>348</value>
        </entry>
        <entry>
            <row>12</row>
            <column>25</column>
            <value>120</value>
        </entry>
        <entry>
            <row>12</row>
            <column>30</column>
            <value>74</value>
        </entry>
        <entry>
            <row>12</row>
            <column>34</column>
            <value>56</value>
        </entry>
        <entry>
            <row>12</row>
            <column>43</column>
            <value>184</value>
        </entry>
        <entry>
            <row>12</row>
            <column>96</column>
            <value>278</value>
        </entry>
        <entry>
            <row>12</row>
            <column>115</column>
            <value>32</value>
        </entry>
        <entry>
            <row>12</row>
            <column>123</column>
            <value>232</value>
        </entry>
        <entry>
            <row>12</row>
            <column>132</column>
            <value>182</value>
        </entry>
        <entry>
            <row>12</row>
            <column>143</column>
            <value>113</value>
        </entry>
        <entry>
            <row>13</row>
            <column>92</column>
            <value>281</value>
        </entry>
        <entry>
            <row>13</row>
            <column>131</column>
            <value>79</value>
        </entry>
        <entry>
            <row>13</row>
            <column>151</column>
            <value>169</value>
        </entry>
        <entry>
            <row>13</row>
            <column>180</column>
            <value>57</value>
        </entry>
        <entry>
            <row>13</row>
            <column>209</column>
            <value>24</value>
        </entry>
        <entry>
            <row>14</row>
            <column>21</column>
            <value>299</value>
        </entry>
        <entry>
            <row>14</row>
            <column>123</column>
            <value>33</value>
        </entry>
        <entry>
            <row>14</row>
            <column>125</column>
            <value>318</value>
        </entry>
        <entry>
            <row>14</row>
            <column>146</column>
            <value>259</value>
        </entry>
        <entry>
            <row>15</row>
            <column>30</column>
            <value>117</value>
        </entry>
        <entry>
            <row>15</row>
            <column>62</column>
            <value>252</value>
        </entry>
        <entry>
            <row>15</row>
